### ISSUE TITLE
[SUGGESTION] Syntax on css file

### ISSUE THREAD

**Issue by LowScarlet** [jensjeflensje/websk#42]
```css
.hello:after {
  content: "{{var}}";
}
```

**Comment by Norbiros** [comment]
Hello!
_I didn't seen people here for 1.5 month!_

I think, it works normally. When you create one file `index.html` and you create `<style>` - it replace text normally, no matter if it is style, text, js or html. Also, when you put css in another file, everything works!

Problem is only with returning files, with **instant system**. This didn't use template system, but it will be fixed in the future! 

I hope I helped,
Norbiros
